version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore .\FlusterDuck.Api\FlusterDuck.Api.csproj --verbosity m
build_script:
  # output will be in ./FlusterDuck.Api/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish .\FlusterDuck.Api\FlusterDuck.Api.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '.\FlusterDuck.Api\bin\Debug\netcoreapp1.1\publish'
   name: WebApi
   type: WebDeployPackage
clone_depth: 1
#test_script:
#  # restore packages for our unit tests
#  - cmd: dotnet restore ./tests/tests.csproj --verbosity m
#  # run the unit tests (requires changing into the test directory)
#  - cmd: cd tests
#  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off